# Generated by Django 3.1.4 on 2020-12-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201222_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(),
        ),
    ]
